
class Book {
  String title,
      writer,
      price,
      image,
      description;

  int pages;
  double rating;


  Book(this.title,
      this.writer,
      this.price,
      this.image,
      this.description,
      this.pages,
      this.rating);
}
  final List<Book> books = [
    Book('A Bend in the River','V.S. Naipul','Rs. 236','assets/images/a_bend_in_the_river.jpg','When Salim, a young Indian man, is offered a small business in Central Africa, he accepts. As he strives to establish himself, he becomes closely involved with the fluid and dangerous politics of the newly-dependent state.',326,3.7),
    Book('A Passage to India','E.M. Forster','Rs. 275','assets/images/a_passage_to_india.jpg','When Adela Quested and her elderly companion Mrs Moore arrive in the Indian town of Chandrapore, they quickly feel trapped by its insular and prejudiced Anglo-Indian community. Determined to escape the parochial English enclave and explore the real India, they seek the guidance of the charming and mercurial Dr Aziz, a cultivated Indian Muslim. But a mysterious incident occurs while they are exploring the Marabar caves with Aziz, and the well-respected doctor soon finds himself at the centre of a scandal that rouses violent passions among both the British and their Indian subjects. A masterly portrait of a society in the grip of imperialism, A Passage to India compellingly depicts the fate of individuals caught between the great political and cultural conflicts of the modern world.',416,3.6),
    Book('Lolita','Vladimir Nabokov','Rs. 280','assets/images/loleeta.jpg','Humbert Humbert - scholar, aesthete and romantic - has fallen completely and utterly in love with Lolita Haze, his landladys gum-snapping, silky skinned twelve-year-old daughter. Reluctantly agreeing to marry Mrs Haze just to be close to Lolita, Humbert suffers greatly in the pursuit of romance; but when Lo herself starts looking for attention elsewhere, he will carry her off on a desperate cross-country misadventure, all in the name of Love. Hilarious, flamboyant, heart-breaking and full of ingenious word play, Lolita is an immaculate, unforgettable masterpiece of obsession, delusion and lust.',331,3.8),
    Book('The Sun also Rises','Ernest Hemingway','Rs. 554','assets/images/the_sun_also_rises.jpg','The quintessential novel of the Lost Generation, The Sun Also Rises is one of Ernest Hemingways masterpieces and a classic example of his spare but powerful writing style. A poignant look at the disillusionment and angst of the post-World War I generation, the novel introduces two of Hemingways most unforgettable characters: Jake Barnes and Lady Brett Ashley. The story follows the flamboyant Brett and the hapless Jake as they journey from the wild nightlife of 1920s Paris to the brutal bullfighting rings of Spain with a motley group of expatriates. It is an age of moral bankruptcy, spiritual dissolution, unrealized love, and vanishing illusions. First published in 1926, The Sun Also Rises helped to establish Hemingway as one of the greatest writers of the twentieth century.',189,3.8),
    Book('The Moonstone','Wilkie Collins','Rs. 261','assets/images/the_moonstone.png','"The Moonstone is a page-turner," writes Carolyn Heilbrun. "It catches one up and unfolds its amazing story through the recountings of its several narrators, all of them enticing and singular." Wilkie Collins’s spellbinding tale of romance, theft, and murder inspired a hugely popular genre–the detective mystery. Hinging on the theft of an enormous diamond originally stolen from an Indian shrine, this riveting novel features the innovative Sergeant Cuff, the hilarious house steward Gabriel Betteridge, a lovesick housemaid, and a mysterious band of Indian jugglers.This Modern Library Paperback Classic is set from the definitive 1871 edition.',528,3.9),
    Book('Wuthering Heights','Emily Brontë','Rs. 690','assets/images/wuthering_heights.jpg','Wuthering Heights is a wild, passionate story of the intense and almost demonic love between Catherine Earnshaw and Heathcliff, a foundling adopted by Catherines father. After Mr Earnshaws death, Heathcliff is bullied and humiliated by Catherines brother Hindley and wrongly believing that his love for Catherine is not reciprocated, leaves Wuthering Heights, only to return years later as a wealthy and polished man. He proceeds to exact a terrible revenge for his former miseries. The action of the story is chaotic and unremittingly violent, but the accomplished handling of a complex structure, the evocative descriptions of the lonely moorland setting and the poetic grandeur of vision combine to make this unique novel a masterpiece of English literature.',464,3.8),
    Book('To Kill a Mockingbird','Harper Lee','Rs. 449','assets/images/to_kill_a_mocking_bird.jpg','The unforgettable novel of a childhood in a sleepy Southern town and the crisis of conscience that rocked it, To Kill A Mockingbird became both an instant bestseller and a critical success when it was first published in 1960. It went on to win the Pulitzer Prize in 1961 and was later made into an Academy Award-winning film, also a classic.Compassionate, dramatic, and deeply moving, To Kill A Mockingbird takes readers to the roots of human behavior - to innocence and experience, kindness and cruelty, love and hatred, humor and pathos. Now with over 18 million copies in print and translated into forty languages, this regional story by a young Alabama woman claims universal appeal. Harper Lee always considered her book to be a simple love story. Today it is regarded as a masterpiece of American literature.',324,4.2),
    Book('The Odyssey','Homer','Rs. 490','assets/images/the_odyysey.jpg','George Herbert Palmer (March 9, 1842 – May 7, 1933) was an American scholar and author. He was a graduate, and then professor at Harvard University. He is also known for his published works, like the translation of The Odyssey (1884) and others about education and ethics, such as The New Education (1887) and The Glory of the Imperfect (1898).This is a pre-1923 historical reproduction that was curated for quality. Quality assurance was conducted on each of these books in an attempt to remove books with imperfections introduced by the digitization process. Though we have made best efforts - the books may have occasional errors that do not impede the reading experience. We believe this work is culturally important and have elected to bring the book back into print as part of our continuing commitment to the preservation of printed works worldwide.',541,3.7),
    Book('War and Peace','Leo Tolstoy','Rs. 275','assets/images/war_and_peace.jpg','War and Peace broadly focuses on Napoleon’s invasion of Russia in 1812 and follows three of the most well-known characters in literature: Pierre Bezukhov, the illegitimate son of a count who is fighting for his inheritance and yearning for spiritual fulfillment; Prince Andrei Bolkonsky, who leaves his family behind to fight in the war against Napoleon; and Natasha Rostov, the beautiful young daughter of a nobleman who intrigues both men.A s Napoleon’s army invades, Tolstoy brilliantly follows characters from diverse backgrounds—peasants and nobility, civilians and soldiers—as they struggle with the problems unique to their era, their history, and their culture. And as the novel progresses, these characters transcend their specificity, becoming some of the most moving—and human—figures in world literature.',1392, 4.1),
    Book('Hamlet','William Shakespeare','Rs. 411','assets/images/hamlet.jpg','Among Shakespeares plays, Hamlet is considered by many his masterpiece. Among actors, the role of Hamlet, Prince of Denmark, is considered the jewel in the crown of a triumphant theatrical career. Now Kenneth Branagh plays the leading role and co-directs a brillant ensemble performance. Three generations of legendary leading actors, many of whom first assembled for the Oscar-winning film Henry V, gather here to perform the rarely heard complete version of the play. This clear, subtly nuanced, stunning dramatization, presented by The Renaissance Theatre Company in association with Bbc Broadcasting, features such luminaries as Sir John Gielgud, Derek Jacobi, Emma Thompson and Christopher Ravenscroft. It combines a full cast with stirring music and sound effects to bring this magnificent Shakespearen classic vividly to life. Revealing new riches with each listening, this production of Hamlet is an invaluable aid for students, teachers and all true lovers of Shakespeare - a recording to be treasured for decades to come.',289,4.0),
    Book('Moby Dick','Herman Melville','Rs. 856','assets/images/moby_dick.jpg','It is the horrible texture of a fabric that should be woven of ships cables and hawsers. A Polar wind blows through it, and birds of prey hover over it. So Melville wrote of his masterpiece, one of the greatest works of imagination in literary history. In part, Moby-Dick is the story of an eerily compelling madman pursuing an unholy war against a creature as vast and dangerous and unknowable as the sea itself. But more than just a novel of adventure, more than an encyclopaedia of whaling lore and legend, the book can be seen as part of its authors lifelong meditation on America. Written with wonderfully redemptive humour, Moby-Dick is also a profound inquiry into character, faith, and the nature of perception.',720,3.4),
    Book('The Great Gatsby','F. Scott Fitzgerald','Rs. 269','assets/images/the_great_gatsby.jpg','Here is a novel, glamorous, ironical, compassionate – a marvelous fusion into unity of the curious incongruities of the life of the period – which reveals a hero like no other – one who could live at no other time and in no other place. But he will live as a character, we surmise, as long as the memory of any reader lasts.It is the story of this Jay Gatsby who came so mysteriously to West Egg, of his sumptuous entertainments, and of his love for Daisy Buchanan – a story that ranges from pure lyrical beauty to sheer brutal realism, and is infused with a sense of the strangeness of human circumstance in a heedless universe. It is a magical, living book, blended of irony, romance, and mysticsm',180,3.0),
    Book('Ulysses','James Joyce','Rs. 271','assets/images/ulysses_main.jpg','The novel is constructed as a modern parallel to Homer’s Odyssey. All of the action of the novel takes place in Dublin on a single day (June 16, 1904). The three central characters—Stephen Dedalus (the hero of Joyce’s earlier Portrait of the Artist as a Young Man), Leopold Bloom, a Jewish advertising canvasser, and his wife, Molly Bloom—are intended to be modern counterparts of Telemachus, Ulysses (Odysseus), and Penelope, and the events of the novel parallel the major events in Odysseus’s journey home after the Trojan War. Occasionally illuminating, at other times these allusions to the ancient work seem designed ironically to offset the often petty and sordid concerns that take up much of Stephen’s and Bloom’s time and continually distract them from their ambitions and aims. The book also conjures up a densely realized Dublin, full of details, many of which are—presumably deliberately—either wrong or at least questionable. But all this merely forms a backdrop to an exploration of the inner workings of the mind, which refuses to acquiesce in the neatness and certainties of classical philosophy.',810,3.7),
    Book('Don Quixote','Miguel de Cervantes','Rs. 279','assets/images/don_quixote_retouch.jpg','Don Quixote has become so entranced by reading chivalric romances, that he determines to become a knight-errant himself. In the company of his faithful squire, Sancho Panza, his exploits blossom in all sorts of wonderful ways. While Quixotes fancy often leads him astray – he tilts at windmills, imagining them to be giants – Sancho acquires cunning and a certain sagacity. Sane madman and wise fool, they roam the world together, and together they have haunted readers imaginations for nearly four hundred years.With its experimental form and literary playfulness, Don Quixote generally has been recognized as the first modern novel. The book has had enormous influence on a host of writers, from Fielding and Sterne to Flaubert, Dickens, Melville, and Faulkner, who reread it once a year, "just as some people read the Bible',1023,3.9),
    Book('In Search of Lost Time','Marcel Proust','Rs. 599','assets/images/in_search_of_lost_time.jpg','Swanns Way tells two related stories, the first of which revolves around Marcel, a younger version of the narrator, and his experiences in, and memories of, the French town Combray. Inspired by the gusts of memory that rise up within him as he dips a Madeleine into hot tea, the narrator discusses his fear of going to bed at night. He is a creature of habit and dislikes waking up in the middle of the night not knowing where he is.He claims that people are defined by the objects that surround them and must piece together their identities bit by bit each time they wake up. The young Marcel is so nervous about sleeping alone that he looks forward to his mothers goodnight kisses, but also dreads them as a sign of an impending sleepless night. One night, when Charles Swann, a friend of his grandparents, is visiting, his mother cannot come kiss him goodnight. He stays up until Swann leaves and looks so sad and pitiful that even his disciplinarian father encourages "Mamma" to spend the night in Marcels room.', 468,4.3),
  ];
